const { baseUrl } = require('./config');
const { requestJson } = require('./http');

function productPayload(prefix, index) {
  return {
    sku: `${prefix}-${index}`,
    name: `Benchmark Product ${index}`,
    description: 'Generated by benchmark scripts',
    priceCents: 1000 + (index % 5000),
    inventory: 1000,
  };
}

async function createProduct(prefix, index) {
  const body = await requestJson(`${baseUrl}/api/products`, {
    method: 'POST',
    body: JSON.stringify(productPayload(prefix, index)),
  });

  return body.data;
}

async function seedProducts(count, prefix = `bench-${Date.now()}`) {
  const products = [];

  for (let index = 0; index < count; index += 1) {
    products.push(await createProduct(prefix, index));
  }

  return products;
}

module.exports = { createProduct, productPayload, seedProducts };
